version: '3.8'

services:
  app:
    image: 'raifmirza/bootcamp-restaurantservice:0.0.1-SNAPSHOT'
    build:
      context: .
    container_name: restaurantservice
    ports:
      - '8081:8081'


  solr:
    image: solr
    ports:
      - "8983:8983"
    volumes:
      - data:/var/solr
    command:
      - solr-precreate
      - gettingstarted
    container_name: solr_container
volumes:
  data: